# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'A+Papers (IB)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', '~> 4.5'
pod 'SCLAlertView'
pod 'Google-Mobile-Ads-SDK'
pod 'Firebase/Analytics'

  # Pods for A+Papers (IB)

end
